<a href="https://colab.research.google.com/github/EllieD27/carisurg-portfolio/blob/main/CariSurg_Week_0_Assignment_1_Cleaning_Gender_Column.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# mounting google drive to access files properly
from google.colab import drive
drive.mount('/content/drive')
print("Drive mounted successfully!")

Mounted at /content/drive
Drive mounted successfully!

In [3]:
# confirming python version
import sys
print(f"Python version: {sys.version}")

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [4]:
# variables
p_id    = 42          # integer
p_name  = "Maria"     # string
heart_rate    = 88.5  # float
is_critical   = True  # boolean

print (f"Patient ID: {p_name}")
print(f"Heart rate: {heart_rate} bpm")
print (f"Critical: {is_critical}")
print (f"heart_rate type: {type(heart_rate)}")

Patient ID: Maria
Heart rate: 88.5 bpm
Critical: True
heart_rate type: <class 'float'>

In [5]:
# list holding multiple values in order
vital_signs = ["pulse", "temperature", "SBP", "DBP", "RR", "FiO2", "GCS"]

print ("All vitals: ", vital_signs)
print ("First vital: ", vital_signs[0]) # first item is retrieved
print(" Last vital: ", vital_signs[-1]) # retrieving the last item
print ("Number of vitals: ", len(vital_signs))

All vitals:  ['pulse', 'temperature', 'SBP', 'DBP', 'RR', 'FiO2', 'GCS']
First vital:  pulse
 Last vital:  GCS
Number of vitals:  7

In [6]:
# for loop
for vital in vital_signs:
    print(f"  - {vital}")

  - pulse
  - temperature
  - SBP
  - DBP
  - RR
  - FiO2
  - GCS

In [7]:
# conditions

def classify_pulse(bpm):
  if bpm < 60:
    return "Bradycardia (too slow)"
  elif bpm > 100:
    return "Tachycardia (too fast)"
  else:
    return "Normal"

# testing
test_pulses = [59, 80, 150]
for p in test_pulses:
  print (f" Pulse {p} bpm -> {classify_pulse(p)}")

 Pulse 59 bpm -> Bradycardia (too slow)
 Pulse 80 bpm -> Normal
 Pulse 150 bpm -> Tachycardia (too fast)

In [8]:
# functions

def greet_trainee(name, unit="Clinical AI Innovation Unit"):
  message = f"Welcome to Mercer General, {name}. You are now part of the {unit}."
  return message

print (greet_trainee("Maria"))
print (greet_trainee("James", "Emergency Department"))

Welcome to Mercer General, Maria. You are now part of the Clinical AI Innovation Unit.
Welcome to Mercer General, James. You are now part of the Emergency Department.

In [9]:
import pandas as pd          # data manipulation
import numpy as np           # numerical operations
import matplotlib.pyplot as plt  # plotting

print("Libraries imported successfully!")

Libraries imported successfully!

In [10]:
FILE_PATH = '/content/drive/MyDrive/Colab Notebooks/EmergencyTriageDataset_Reduced_Dirty.csv'
df_raw = pd.read_csv(FILE_PATH)
print(f"Dataset loaded: {df_raw.shape[0]} rows x {df_raw.shape[1]} columns")
print(f"Columns: {list(df_raw.columns)}")

Dataset loaded: 2205 rows x 11 columns
Columns: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

In [11]:
df_raw.head(10)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0
5   6   42    Male  15.0  100   60.0   73.33   99.0  37.0  20.0   21.0
6   7   75  Female  15.0  120   80.0   93.33   99.0  37.0  25.0   21.0
7   8   25    Male  15.0  100   50.0   66.67   85.0  37.0  25.0   21.0
8   9   67       0  15.0  110   70.0   83.33   78.0  37.0  16.0   21.0
9  11   82  Female  15.0  153   82.0  105.67  130.0  37.0  19.0   21.0

In [12]:
print(df_raw.dtypes)

ID          int64
Age         int64
Gender     object
GCS        object
SBP        object
DBP       float64
MAP       float64
pulse      object
Temp       object
RR        float64
Fio2      float64
dtype: object

In [18]:
# seeing what values are actually in the gender column
print("Unique values in Gender:")
print(df_raw['Gender'].unique())
print(f"\nTotal unique values used: {df_raw['Gender'].nunique()}")

Unique values in Gender:
['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']

Total unique values used: 6

In [14]:
# conting how many of each we have
print("Gender Value counts: ")
print(df_raw['Gender'].value_counts())

Gender Value counts:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [15]:
# grouping male and female variations, and assigning them to 1 and 0 for easier interpretation
gender_map = {
    'Male':   1,
    'MALE':   1,
    '1':      1,
    'Female': 0,
    'FEMALE': 0,
    '0':      0
}

In [19]:
df_raw['Gender_Clean'] = df_raw['Gender'].map(gender_map)

print("After cleaning Gender Column:")
print(df_raw['Gender_Clean'].value_counts())

print(f"Data type: {df_raw['Gender'].dtype}")
print ("\n")
df_raw.head()

After cleaning Gender Column:
Gender_Clean
1    1176
0    1029
Name: count, dtype: int64
Data type: object

,ID,Age,Gender,GCS,SBP,DBP,MAP,pulse,Temp,RR,Fio2,Gender_Clean
0,1,34,0,15.0,93,67.0,75.67,128.0,36.8,14.0,21.0,0
1,2,20,Male,15.0,130,90.0,103.33,80.0,37.0,16.0,21.0,1
2,3,77,Female,14.0,163,105.0,124.33,92.0,36.8,18.0,21.0,0
3,4,23,0,8.0,100,60.0,73.33,100.0,37.0,12.0,100.0,0
4,5,86,FEMALE,15.0,150,90.0,110.00,85.0,37.0,19.0,21.0,0